package com.example.android.reciped;

import android.app.Activity;
import android.content.Intent;
import android.os.Bundle;
import android.text.TextUtils;
import android.util.Log;
import android.view.KeyEvent;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.inputmethod.EditorInfo;
import android.widget.AutoCompleteTextView;
import android.widget.Button;
import android.widget.EditText;
import android.widget.TextView;

import com.firebase.client.AuthData;
import com.firebase.client.Firebase;
import com.firebase.client.FirebaseError;


/**
 * A login screen that offers login via email/password.
 * TODO: Most of this code was autogenerated by the Android system. I removed a progress bar, asynctask
 * and autocomplete.
 */
public class LoginActivity extends Activity {

    private static final String LOG_TAG = LoginActivity.class.getSimpleName();
    public static final int LOGIN_REQUEST = 2;


    /**
     * Keep track of the login task to ensure we can cancel it if requested.
     */
    //private UserLoginTask mAuthTask = null;

    // UI references.
    private AutoCompleteTextView mEmailView;
    private EditText mPasswordView;
    private View mLoginFormView;

    private Firebase mFirebaseRef;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_login);

        mFirebaseRef = new Firebase(RecipeListActivity.FIREBASE_URL);


        // Set up the login form.
        mEmailView = (AutoCompleteTextView) findViewById(R.id.email);

        // Set up autocomplete
        final UserAutocompleteAdapter autocompleteFBAdapter = new UserAutocompleteAdapter(this);
        mEmailView.setAdapter(autocompleteFBAdapter);

        mPasswordView = (EditText) findViewById(R.id.password);
        mPasswordView.setOnEditorActionListener(new TextView.OnEditorActionListener() {
            @Override
            public boolean onEditorAction(TextView textView, int id, KeyEvent keyEvent) {
                if (id == R.id.login || id == EditorInfo.IME_NULL) {
                    attemptLogin();
                    return true;
                }
                return false;
            }
        });

        Button mEmailSignInButton = (Button) findViewById(R.id.email_sign_in_button);
        mEmailSignInButton.setOnClickListener(new OnClickListener() {
            @Override
            public void onClick(View view) {
                attemptLogin();
            }
        });

        mLoginFormView = findViewById(R.id.login_form);

    }



    /**
     * Attempts to sign in or register the account specified by the login form.
     * If there are form errors (invalid email, missing fields, etc.), the
     * errors are presented and no actual login attempt is made.
     */
    public void attemptLogin() {
//        if (mAuthTask != null) {
//            return;
//        }

        // Reset errors.
        mEmailView.setError(null);
        mPasswordView.setError(null);

        // Store values at the time of the login attempt.
        final String email = mEmailView.getText().toString();
        final String password = mPasswordView.getText().toString();

        boolean cancel = false;
        View focusView = null;

        // Check for a valid password, if the user entered one.
        if (!TextUtils.isEmpty(password) && !isPasswordValid(password)) {
            mPasswordView.setError(getString(R.string.error_invalid_password));
            focusView = mPasswordView;
            cancel = true;
        }

        // Check for a valid email address.
        if (TextUtils.isEmpty(email)) {
            mEmailView.setError(getString(R.string.error_field_required));
            focusView = mEmailView;
            cancel = true;
        } else if (!isEmailValid(email)) {
            mEmailView.setError(getString(R.string.error_invalid_email));
            focusView = mEmailView;
            cancel = true;
        }

        if (cancel) {
            // There was an error; don't attempt login and focus the first
            // form field with an error.
            focusView.requestFocus();
        } else {
            // Show a progress spinner, and kick off a background task to
            // perform the user login attempt.

            /*showProgress(true);
            mAuthTask = new UserLoginTask(email, password);
            mAuthTask.execute((Void) null);*/

            //TODO This is all of the login logic. It works like the chat app where it will try first
            //to create an account and then log in the user if an account already exists.
            mFirebaseRef.createUser(email, password, new Firebase.ResultHandler() {
                @Override
                public void onSuccess() {

                    Log.e(LOG_TAG, "Created user in the backend with email " + email);
                    mFirebaseRef.authWithPassword(email, password, new Firebase.AuthResultHandler() {
                        @Override
                        public void onAuthenticated(AuthData authData) {
                            Firebase usersRef = mFirebaseRef.child(User.FIREBASE_USER_PATH).child(authData.getUid());
                            //TODO This creates a new ref in the user table
                            usersRef.setValue(new User(email, authData.getUid()));

                            Log.e(LOG_TAG, "Created user " + authData.getUid() + " with email " + email);

                            Intent returnIntent = new Intent();
                            setResult(RESULT_OK, returnIntent);
                            finish();
                        }

                        @Override
                        public void onAuthenticationError(FirebaseError firebaseError) {
                            // there was an error
                            Log.e(LOG_TAG, "Error creating user with email " + email);

                        }
                    });

                }

                @Override
                public void onError(FirebaseError firebaseError) {
                    mFirebaseRef.authWithPassword(email, password, new Firebase.AuthResultHandler() {
                                @Override
                                public void onAuthenticated(AuthData authData) {
                                    Firebase usersRef = mFirebaseRef.child(User.FIREBASE_USER_PATH).child(authData.getUid());
                                    Log.e(LOG_TAG, "Logged in user " + authData.getUid() + " with email " + email);
                                    Intent returnIntent = new Intent();
                                    setResult(RESULT_OK, returnIntent);
                                    finish();
                                }

                                @Override
                                public void onAuthenticationError(FirebaseError firebaseError) {
                                    // there was an error
                                    Log.e(LOG_TAG, "Error logging in user with email " + email);
                                    switch (firebaseError.getCode()) {
                                        case FirebaseError.USER_DOES_NOT_EXIST:
                                            Log.e(LOG_TAG, "User doesn't exist");
                                            break;
                                        case FirebaseError.INVALID_PASSWORD:
                                            Log.e(LOG_TAG, "Password is invalid");
                                            break;
                                        default:
                                            Log.e(LOG_TAG, "Some other error " + firebaseError.getMessage() + firebaseError.getDetails());
                                            break;
                                    }

                                }
                            });
                }
            });
        }
    }

    private boolean isEmailValid(String email) {
        //Replace this with your own logic
        return email.contains("@");
    }

    private boolean isPasswordValid(String password) {
        //Replace this with your own logic
        return password.length() > 4;
    }

}

